version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: furniro-postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: furniro_db
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
